#!/usr/bin/env python3
"""Infer a prototype for every function from its own asm.

m2c drafts a call from the registers the caller sets, so without knowing the
callee it gets C++-style calls wrong. A method calling another method on the
same object leaves `this` untouched in $a0 and only sets $a1:

    jal   func_00245848
     addiu $a1, $a0, 0x140        # func_00245848(this, this + 0x140)

and m2c, seeing one argument set, writes `func_00245848(arg0 + 0x140)`,
which compiles the value into $a0. Knowing that func_00245848 takes two
arguments is enough for m2c to pass `arg0` through, and the draft matches.

The count comes from the callee: an argument register it reads before it
writes is a parameter. $f12/$f14 read first make the first/second parameter a
float. The return type is s32 if the function sets $v0, f32 if it only sets
$f0, and void otherwise. This is a heuristic over a linear pass that ignores
branches, and it is only an aid for drafting: a wrong prototype costs a
non-matching draft, never a wrong ROM, since `make verify` decides.

Writes include/functions.h, which the drafts include and m2c reads as context.

Usage:
    python3 tools/gen_prototypes.py
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "include" / "functions.h"
REGS = ("zero at v0 v1 a0 a1 a2 a3 t0 t1 t2 t3 t4 t5 t6 t7 "
        "s0 s1 s2 s3 s4 s5 s6 s7 t8 t9 k0 k1 gp sp fp ra").split()

# Mnemonics whose first operand is read, not written.
READ_FIRST = re.compile(
    r"^(s[bhwd]|swc1|sdc1|swl|swr|b\w*|j|jr|jalr|mtc1|dmtc1|ctc1|c\.\w+|"
    r"div|divu|ddiv|ddivu|mult|multu|dmult|dmultu|teq|tne|cache)$")
INSN = re.compile(r"^\s+([a-z][a-z0-9.]*)\s*(.*)$")
REG = re.compile(r"\$(\d+|f\d+|[a-z][a-z0-9]*)")
ARGS = ["a0", "a1", "a2", "a3"]


def reg_name(tok):
    if tok.isdigit():
        return REGS[int(tok)]
    return tok


def analyse(body):
    read_first, written = set(), set()
    for line in body.splitlines():
        m = INSN.match(line)
        if not m or m.group(1).startswith("."):
            continue
        op, rest = m.group(1), m.group(2).split("#")[0]
        regs = [reg_name(r) for r in REG.findall(rest)]
        if not regs:
            continue
        if READ_FIRST.match(op):
            reads, writes = regs, []
            if op in ("mtc1", "dmtc1", "ctc1") and len(regs) > 1:
                reads, writes = regs[:1], regs[1:2]
        elif op in ("jal",):
            reads, writes = [], []
        else:
            reads, writes = regs[1:], regs[:1]
        for r in reads:
            if r not in written:
                read_first.add(r)
        written.update(writes)
    return read_first, written


FRAME = re.compile(r"^\s+addiu\s+\$(?:29|sp),\s*\$(?:29|sp),\s*-(0x[0-9A-Fa-f]+|\d+)", re.M)
STACK_LOAD = re.compile(r"^\s+(?:lw|lh|lhu|lb|lbu|lwc1|ld|ldc1)\s+[^,]+,\s*(0x[0-9A-Fa-f]+|\d+)\(\$(?:29|sp)\)", re.M)


def stack_params(body):
    """Parameters past the fourth, which the o32 ABI passes on the stack.

    The caller leaves 16 bytes of home space for $a0-$a3, so the fifth
    argument sits at 0x10 above the callee's incoming $sp, i.e. at
    frame + 0x10 once it has pushed its frame.
    """
    m = FRAME.search(body)
    frame = int(m.group(1), 0) if m else 0
    top = 0
    for off in STACK_LOAD.findall(body):
        off = int(off, 0)
        if off >= frame + 0x10:
            top = max(top, 4 + (off - frame - 0x10) // 4 + 1)
    return top


def prototype(name, body):
    reads, writes = analyse(body)
    n = 0
    for i, a in enumerate(ARGS):
        if a in reads:
            n = i + 1
    n = max(n, stack_params(body))
    params = []
    for i in range(n):
        if i == 0 and "f12" in reads:
            params.append("f32")
        elif i == 1 and "f14" in reads and "f12" in reads:
            params.append("f32")
        else:
            params.append("s32")
    if n == 0 and "f12" in reads:
        params = ["f32"] + (["f32"] if "f14" in reads else [])
    if "v0" in writes:
        ret = "s32"
    elif "f0" in writes:
        ret = "f32"
    else:
        ret = "void"
    return f"{ret} {name}({', '.join(params) or 'void'});"


def main():
    protos = {}
    for path in sorted(ROOT.glob("us/asm/*.s")) + sorted(ROOT.glob("us/asm/nonmatchings/**/*.s")):
        text = path.read_text(errors="replace")
        for m in re.finditer(r"^\.globl (func_[0-9A-F]{8})\n(.*?)^\.end \1\n", text, re.S | re.M):
            protos.setdefault(m.group(1), prototype(m.group(1), m.group(2)))
    lines = [
        "#ifndef FUNCTIONS_H",
        "#define FUNCTIONS_H",
        "",
        "/* Generated by tools/gen_prototypes.py from each function's own asm:",
        " * the argument registers it reads before writing, and what it returns.",
        " * A drafting aid for m2c; a function written in C carries its real",
        " * signature, and this file must not contradict it. */",
        "",
        '#include "common.h"',
        "",
    ]
    lines += [protos[n] for n in sorted(protos)]
    lines += ["", "#endif", ""]
    OUT.write_text("\n".join(lines))
    print(f"{len(protos)} prototypes -> {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
