#!/usr/bin/env python3
"""Turn the recompiler's complaints into boundary corrections.

`tools/fix_asm.py` has always said the bad-boundary list "is generated by
running the recompiler, so it corrects itself as the segmentation improves".
Nothing generated it. Only `jumptable_targets.py` ever wrote to the file, and
that finds a different class -- switch targets sitting in rodata. This closes
the loop the docstring describes.

The signal is a function branching to an address before its own start:

    Unhandled branch in func_00262CFC at 0x00262D04 to 0x00262CF4

A branch cannot leave its function, so if the target precedes the start we
declared, the start is wrong -- the real function began earlier and something
seeded a boundary in the middle of it. That address goes in the bad list, which
`function_seed.py` then refuses to seed and `fix_asm.py` refuses to promote.

This is the false-positive half of the after-a-return rule. That rule assumes a
`jr ra` ends a function, which is true of most MIPS the SN64 compiler emits but
not of a function with an early return, where execution carries on past it into
more of the same function. There is no way to tell the two apart from the bytes
-- both are a return followed by instructions -- so the rule seeds both and this
takes back the ones that turn out to be wrong.

Forward branches are left alone. Those are tail calls, and the address they
name is a real function start that is simply missing a symbol; deleting a
boundary would not help.

Usage:
    python3 tools/recomp_feedback.py recomp.log            # report
    python3 tools/recomp_feedback.py recomp.log --write    # merge into the list
"""

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
# Kept apart from bad_boundaries.us.txt on purpose. That file is what
# `jumptable_targets.py` writes, and it is a heuristic: a run of code addresses
# in a data region. That shape covers two different things -- a `switch` table,
# whose entries are branch targets inside a function, and a table of function
# pointers, whose entries are genuine function starts. Treating all of them as
# non-boundaries cost 308 sound seeds and 272 KB of emitted C. What lands here
# instead is only what the recompiler itself rejected, which is ground truth.
REJECTED = ROOT / "versions" / "rejected_boundaries.us.txt"
# Call targets the recompiler could not resolve to any function. These are the
# opposite correction: an address that needs a symbol, not one that has a wrong
# one. `function_seed.py` merges this file into its output.
MISSING = ROOT / "versions" / "recomp_seeds.us.txt"

# Unhandled branch in func_00262CFC at 0x00262D04 to 0x00262CF4
BRANCH = re.compile(
    r"Unhandled branch in (\S+?) at 0x([0-9A-Fa-f]+) to 0x([0-9A-Fa-f]+)")
# [Warn] Function func_00299EB0 is branching outside of the function (to 0x...)
OUTSIDE = re.compile(
    r"Function (\S+?) is branching outside of the function \(to 0x([0-9A-Fa-f]+)\)")
# No function found for jal target: 0x00416B44
NOFUNC = re.compile(r"No function found for jal target: 0x([0-9A-Fa-f]+)")
# Failed to determine size of jump table at 0x800A8468 for instruction at 0x0027BB0C
JTBL = re.compile(
    r"Failed to determine size of jump table at 0x([0-9A-Fa-f]+) "
    r"for instruction at 0x([0-9A-Fa-f]+)")
FAILED = re.compile(r"Failed to analyze (\S+)")


def jumptable_span(rodata_vram):
    """Highest code address in the table at `rodata_vram`, or None.

    N64Recomp sizes a `switch` table by walking it while the entries stay
    inside the function that reads it. If a seed cut that function short, every
    entry past the cut falls outside and it gives up with nothing to size. So
    the table itself says how far the function has to reach: at least as far as
    its furthest entry.
    """
    import struct
    import sys
    sys.path.insert(0, str(ROOT / "tools"))
    from function_seed import load_code_segments, vram_to_segment, ROM

    rom = ROM.read_bytes()
    segs = load_code_segments()

    # rodata is not in load_code_segments (it only returns asm), so map by hand
    # through the same yaml.
    import yaml
    with (ROOT / "versions" / "turok2.us.yaml").open() as fh:
        doc = yaml.safe_load(fh)
    tops = sorted((s for s in doc["segments"] if isinstance(s, dict)),
                  key=lambda s: s["start"])
    off = None
    for i, seg in enumerate(tops):
        if "vram" not in seg:
            continue
        end = tops[i + 1]["start"] if i + 1 < len(tops) else seg["start"]
        size = end - seg["start"]
        if seg["vram"] <= rodata_vram < seg["vram"] + size:
            off = seg["start"] + (rodata_vram - seg["vram"])
            break
    if off is None:
        return None

    highest = None
    while off + 4 <= len(rom):
        word = struct.unpack_from(">I", rom, off)[0]
        if not vram_to_segment(segs, word):
            break
        highest = word if highest is None else max(highest, word)
        off += 4
    return highest


def addr_of(name):
    m = re.search(r"([0-9A-Fa-f]{8})$", name)
    return int(m.group(1), 16) if m else None


def harvest(text):
    backward, forward = set(), set()
    seeded_now = load_seeded()
    for name, _at, target in BRANCH.findall(text):
        start = addr_of(name)
        if start is None:
            continue
        t = int(target, 16)
        if t < start:
            backward.add(start)
        elif t in seeded_now:
            # Forward, and the target is a function entry: a tail call. The
            # address is real and simply wants a symbol, which the seed pass
            # will supply. Nothing to correct here.
            forward.add(t)
        else:
            # Forward, and the target is not any function's entry. A branch
            # cannot leave its function and a tail call can only land on an
            # entry, so this function has to reach at least as far as `t` and
            # something between cut it short. Everything seeded in that span
            # is inside one function.
            #
            # func_004208E0 jumps to 0x00420C18, which objdump names
            # `.L00420BC8+0x50` -- 0x50 into a label, so not an entry. The
            # label at 0x00420BC8 was the false boundary.
            backward |= {a for a in seeded_now if start < a <= t}
    for name, target in OUTSIDE.findall(text):
        start = addr_of(name)
        if start is not None and int(target, 16) < start:
            backward.add(start)

    # A table that cannot be sized means the function reading it was cut short.
    # Everything we seeded between its start and the table's furthest entry is
    # inside one function and has to go.
    seeded = load_seeded()
    ordered = sorted(seeded)
    for rodata, insn in JTBL.findall(text):
        # Pair the table with the function that actually contains the reading
        # instruction, not with whatever "Failed to analyze" came last. The two
        # messages reach the log on different streams, so their order is not
        # the order they happened: a table reported at 0x00446680 was being
        # matched to func_00452060, which starts 0xB9E0 past it.
        import bisect
        i = bisect.bisect_right(ordered, int(insn, 16)) - 1
        if i < 0:
            continue
        start = ordered[i]
        highest = jumptable_span(int(rodata, 16))
        if highest is None or highest <= start:
            continue
        backward |= {a for a in seeded if start < a <= highest}
    return backward, forward


def load_seeded():
    """Addresses we currently seed, so a span can be cleared of them."""
    out = set()
    path = ROOT / "versions" / "symbols_from_scan.us.txt"
    if not path.exists():
        return out
    for line in path.read_text(errors="replace").splitlines():
        m = re.search(r"=\s*0x([0-9A-Fa-f]+)", line)
        if m:
            out.add(int(m.group(1), 16))
    return out


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("log", type=Path, help="N64Recomp output")
    ap.add_argument("--write", action="store_true", help="merge into the list")
    args = ap.parse_args()

    text = args.log.read_text(errors="replace")
    backward, forward = harvest(text)
    missing = {int(a, 16) for a in NOFUNC.findall(text)}
    print(f"call targets with no function: {len(missing):,}")
    print(f"false boundaries (branch goes back past the start): {len(backward):,}")
    for a in sorted(backward):
        print(f"  0x{a:08X}")
    if forward:
        print(f"\ntail calls to an address with no symbol: {len(forward):,}")
        for a in sorted(forward)[:10]:
            print(f"  0x{a:08X}")
        print("  (these want a seed, not a correction -- left alone)")

    if args.write and missing:
        have = set()
        if MISSING.exists():
            for line in MISSING.read_text().split():
                try:
                    have.add(int(line, 16))
                except ValueError:
                    pass
        merged = have | missing
        MISSING.write_text("\n".join(f"0x{a:08X}" for a in sorted(merged)) + "\n")
        print(f"seeds added       : {len(merged) - len(have):,}  (total {len(merged):,})")

    if args.write and backward:
        have = set()
        if REJECTED.exists():
            for line in REJECTED.read_text().split():
                try:
                    have.add(int(line, 16))
                except ValueError:
                    pass
        merged = have | backward
        REJECTED.write_text("\n".join(f"0x{a:08X}" for a in sorted(merged)) + "\n")
        print(f"\nadded             : {len(merged) - len(have):,}")
        print(f"rejected now      : {len(merged):,}")


if __name__ == "__main__":
    main()
